#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# RT-Thread env tool
# Copyright (c) 2026 dongly
#
# Change Logs:
# Date           Author       Notes
# 2026-09-12     Dongly       first version; host the env repo upgrade chain
#                             moved from cmd_package_upgrade

"""Upgrade the env toolchain itself (env repository)."""

import os
import platform
import subprocess
import sys

from vars import Import
from info import get_source
from cmds.cmd_package.cmd_package_utils import execute_command, git_pull_repo
from cmds.cmd_package.cmd_package_update import need_using_mirror_download


def add_parser(sub):
    parser = sub.add_parser('upgrade', help=__doc__, description=__doc__)
    parser.set_defaults(func=cmd)


def cmd(args):
    upgrade_env_script(force_upgrade=True)


def upgrade_env_script(force_upgrade=False):
    """Update env function scripts."""

    env_root = Import('env_root')

    src = get_source('env', use_mirror=need_using_mirror_download())

    env_scripts_root = os.path.join(env_root, 'tools', 'scripts')
    if force_upgrade:
        execute_command('git fetch --all', cwd=env_scripts_root)
        execute_command('git reset --hard origin/%s' % src.branch, cwd=env_scripts_root)
    print("Begin to upgrade env scripts.")
    git_pull_repo(env_scripts_root, src.url)
    print("==============================>  Env scripts upgrade done \n")

    _post_upgrade_refresh(env_root, env_scripts_root)


def _post_upgrade_refresh(env_root, env_scripts_root):
    """Best-effort post-upgrade steps after the env repo changed.

    1. pip install -e so new console scripts and dependency changes take
       effect (the editable .pth only redirects code, not entry points).
    2. Regenerate the root activator to match the upgraded env scripts.
    The user customization file ($ENV_ROOT/env.user.*) is never touched.
    """
    print("Refreshing rt-env installation (pip install -e) ...")
    try:
        subprocess.run(
            [sys.executable, '-m', 'pip', 'install', '-q', '-e', env_scripts_root],
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True)
        print("==============================>  rt-env package refreshed \n")
    except (OSError, subprocess.SubprocessError) as e:
        output = getattr(e, 'output', b'')
        detail = output.decode(errors='replace') if isinstance(output, bytes) else str(e)
        print("Warning: pip install -e failed:\n{0}".format(detail.strip() or str(e)))
        print("Run manually: \"{0}\" -m pip install -e \"{1}\"".format(sys.executable, env_scripts_root))

    print("Refreshing root activator ...")
    try:
        _write_root_activator(env_root, env_scripts_root)
        print("==============================>  Root activator refreshed \n")
    except (OSError, UnicodeDecodeError) as e:
        print("Warning: could not refresh root activator: {0}".format(e))




def _write_root_activator(env_root, env_scripts_root):
    """Regenerate $ENV_ROOT/env.sh(ps1) to match the upgraded env scripts.

    The root activator delegates to tools/scripts by script-relative path
    (no absolute paths, no injected variables). Mirrors tools/touch_env.py
    copy_env_scripts (kept local: tools/ is not importable from the
    installed package).
    """
    name = 'env.ps1' if platform.system() == 'Windows' else 'env.sh'
    src = os.path.join(env_scripts_root, name)
    dst = os.path.join(env_root, name)
    if not os.path.isfile(src):
        return
    if name.endswith('.ps1'):
        content = (
            "# Generated by the RT-Thread ENV installer. Do not edit.\r\n"
            ". \"$PSScriptRoot\\tools\\scripts\\{0}\"\r\n".format(name)
        )
        encoding = 'utf-8-sig'
    else:
        content = (
            "# Generated by the RT-Thread ENV installer. Do not edit.\n"
            "if [ -n \"${ZSH_VERSION:-}\" ]; then\n"
            "    _RT_SELF=\"${(%):-%x}\"\n"
            "else\n"
            "    _RT_SELF=\"${BASH_SOURCE:-$0}\"\n"
            "fi\n"
            '. "$(cd "$(dirname "$_RT_SELF")" && pwd)/tools/scripts/' + name + '"\n'
        )
        encoding = 'utf-8'
    with open(dst, 'w', encoding=encoding, newline='') as f:
        f.write(content)
